### ISSUE TITLE
Review Options sugar extensions

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#109]
https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options/OptionsServiceCollectionExtensions.cs

@divega

**Comment by divega** [comment]
@HaoK here is what I found:

1. I couldn't find usages of ConfigureOptions() methods in MVC (I think you mentioned it was used there?). Are you sure these need to remain and be public?
2. In any case, given it is a fairly low level, I think we can get rid of the generic overload and leave only the type and instance versions. That would mean we don't need to find a better name for `TSetup` :smile:
3. The exception message we build in the private `FindIConfigureOptions()` method seems very ad-hoc. I think we should improve it by moving the throwing to each specific overload, so we can have something like:
 1. "The type provided in the 'configureType' argument does not implement the IConfigureOptions<> interface."
 2. "The instance provided in 'configureInstance' argument does not implement the IConfigureOptions<> interface."
 3. And optionally "Use `Configure<TOptions>(Action<TOptions>)` to configure options based on an action", but if we remove the generic overload of `ConfigureOptions` we probably don't need the latter.
4. I would like us to consider renaming the `ConfigureOptions()` methods to `AddConfigureOptions()`` (I would actually prefer `AddOptionsConfiguration()` or `AddOptionsSetup()` because "ConfigureOptions" is not a substantive, but it seems we are stuck with it :disappointed:).
5. Assuming everything is a "ConfigureOptions" the argument for `Configure<TOptions>()` should be `configureAction` and not `setupAction`.

**Comment by HaoK** [comment]
Looks like MVC directly adds their setups via TryAdd...  How about we just make these private/remove the unused ones for now, we can always add these back if requested.

**Comment by divega** [comment]
Sounds good to me. The TryConfigure PR could do something similar I guess.

**Comment by HaoK** [comment]
0002d4ebc03bdd44270714748a84625f16fc2ebe
