### ISSUE TITLE
How can update Configuration

### ISSUE THREAD

**Issue by lmxin123** [aspnet/Options#126]
When I modify appsetting.json file,
I have call builder.reload() mathod and Configuration data has updated.
but when use DependencyInjection to get IOptions<class> ,
the value has not update.
so ,how can update Configuration on runtime?

**Comment by halter73** [comment]
I don't think it's documented yet, but I think you are supposed to to use  `IOptionsMonitor<TOptions>`. You can see how to use it in [this test](https://github.com/aspnet/Options/blob/60130801e772a6cc811c182c6d260c44e4559d3b/test/Microsoft.Extensions.Options.Test/OptionsMonitorTest.cs#L199).

Unfortunately, if you are injecting `IOptions<TOptions>`, you won't get an updated value after config changes because `IOptions<>` is registered as a singleton. So, as of right now, you have to use `IOptionsMonitor<TOptions>` and set up the `OnChange` callback.

I'm not sure what the recommendation is for getting the most up-to-date `TOptions` when the `OnChange` callback isn't already set up. @HaoK thoughts? Did I get anything wrong?

**Comment by HaoK** [comment]
Yeah that's right, you basically have to choose in advance that you want to listen for options changes by using `IOptionsMonitor<TOptions>`  You won't be able to see any changes via `IOptions`.
